### ISSUE TITLE
Fix gh-pages

### ISSUE THREAD

**Issue by PengiCoder** [PengiOS/wiki#1]
There is a command **`mkdocs gh-pages`** which we could use for site @MrPiggy105

**Comment by PengiCoder** [comment]
error

Error: Artifact could not be deployed. Please ensure the content does not contain any hard links, symlinks and total size is less than 10GB.

**Comment by MrPiggy105** [comment]
There are no symlinks though, and it's definitely less than 10GB. I'll try `mkdocs gh-pages`

**Comment by PengiCoder** [comment]
i fixed it dont edit it

**Comment by MrPiggy105** [comment]
You did not fix it... it just doesn't deploy it.

**Comment by MrPiggy105** [comment]
Fixed. It deploys with:

- force commit
- repo write permissions for the action

but it works

what have I done
